services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app:7.4
    ports:
      - "80:8000"
    volumes:
      - /home/ubuntu/projectdesarrollo:/app
      - /app/vendor
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: "http://localhost"
      DB_DATABASE: laravel
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_pass
    container_name: laravel
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - db_data_prod:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    container_name: mysql
    command: --user=mysql --datadir=/var/lib/mysql

volumes:
  db_data_prod: