version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app:7.4
    ports:
      - "80:8000"
    volumes:
      - .:/app
      - /app/vendor
    environment:
      APP_ENV: "production"
      APP_DEBUG: "false"
      DB_DATABASE: "laravel"
      DB_USERNAME: "laravel_user"
      DB_PASSWORD: "laravel_pass"
    container_name: laravel-prod
    depends_on:
      - db
    user: "www-data"  # Ejecuta el contenedor como el usuario www-data

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - db_data_prod:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "laravel"
      MYSQL_USER: "laravel_user"
      MYSQL_PASSWORD: "laravel_pass"
    container_name: mysql-prod

volumes:
  db_data_prod:
