services:
  app:
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    environment:
      APP_ENV: testing
      APP_DEBUG: true
      DB_DATABASE: laravel
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_pass
    container_name: laravel-test
    depends_on:
      - db

  db:
    ports:
      - "3307:3306"
    volumes:
      - db_data_test:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test_root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    container_name: mysql-test

volumes:
  db_data_test:
