services:
  app:
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    environment:
      APP_ENV: testing
      APP_DEBUG: true
      DB_DATABASE: test_db
      DB_USERNAME: test_user
      DB_PASSWORD: test_pass
    container_name: laravel-test
    depends_on:
      - db
    networks:
      - test-network

  db:
    ports:
      - "3307:3306"
    volumes:
      - db_data_test:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test_root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    container_name: mysql-test
    networks:
      - test-network

volumes:
  db_data_test:

networks:
  test-network:
    driver: bridge
