version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:delegated
      - ./src/vendor:/var/www/html/vendor
      - ./src/node_modules:/var/www/html/node_modules
    networks:
      - laravel_network
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY
      - USER_ID=1000
      - GROUP_ID=1000
    user: "${USER_ID}:${GROUP_ID}"
    command: >
      sh -c "apache2-foreground"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password 
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:

volumes:
  mysql_data:
