version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel_network
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY
      - USER_ID=1000
      - GROUP_ID=1000
    working_dir: /var/www/html
    command: >
      sh -c "composer install &&
            npm install --legacy-peer-deps &&
            npm run dev &&
            php artisan migrate &&
            php artisan serve --host=0.0.0.0 --port=80"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password 
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:

volumes:
  mysql_data:
