version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    working_dir: /var/www/html
    depends_on:
      - db
    networks:
      - laravel-network
    command: >
      bash -c "
      composer install &&
      npm install --legacy-peer-deps &&
      php artisan key:generate &&
      service apache2 reload &&
      apache2-foreground
      "

  db:
    image: mysql:8.0
    container_name: laravel-db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel_user
      - MYSQL_PASSWORD=laravel_pass
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  db_data:
