services:
  app:
    ports:
      - "80:8000"
    volumes:
      - /var/www/html:/app:ro
    environment:
      APP_ENV: production
      APP_DEBUG: false
      DB_DATABASE: laravel
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_pass
    container_name: laravel-prod
    depends_on:
      - db
    networks:
      - prod-network

  db:
    ports:
      - "3306:3306"
    volumes:
      - db_data_prod:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    container_name: mysql-prod
    networks:
      - prod-network

volumes:
  db_data_prod:

networks:
  prod-network:
    driver: bridge
