version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app:7.4
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_DATABASE: laravel
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_pass
    container_name: laravel-dev
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - db_data_dev:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    container_name: mysql-dev

volumes:
  db_data_dev:
