name: Deploy to EC2

on:
  push:
    branches:
      - master
      - docker
  pull_request:
    branches:
      - master
      - docker

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

    - name: Install Docker and Docker Compose on EC2
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Instalar Docker y Docker Compose si no están instalados
          if ! command -v docker &> /dev/null; then
            echo "Instalando Docker..."
            sudo apt-get update
            sudo apt-get install -y docker.io curl
            sudo systemctl enable --now docker
          fi

          if ! command -v docker-compose &> /dev/null; then
            echo "Instalando Docker Compose..."
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi
        EOF

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Remonta el sistema de archivos como lectura/escritura
          sudo mount -o remount,rw /

          # Asegurar permisos de escritura en /var/www/html
          sudo mkdir -p /var/www/html
          sudo chmod -R 777 /var/www/html
          sudo chown -R 777 /var/www
          sudo chown -R 777 /var
          sudo chown -R ubuntu:ubuntu /var/www/html

          # Eliminar el proyecto anterior y clonar el repositorio
          if [ -d "/var/www/html/projectdesarrollo" ]; then
            sudo rm -rf /var/www/html/projectdesarrollo
          fi
          sudo git clone -b docker https://github.com/tjhoan/projectDesarrollo.git /var/www/html/projectdesarrollo

          # Establecer permisos adecuados en el proyecto
          sudo chmod -R 777 /var/www/html/projectdesarrollo
          sudo chown -R ubuntu:ubuntu /var/www/html/projectdesarrollo

          # Ejecutar el script init.sh
          cd /var/www/html/projectdesarrollo
          sudo chmod +x init.sh
          sudo ./init.sh
        EOF

      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        COMPOSER_PROCESS_TIMEOUT: 0
        COMPOSER_NO_INTERACTION: 1
        COMPOSER_NO_AUDIT: 1
