name: Deploy to EC2

on:
  push:
    branches:
      - master
      - docker
  pull_request:
    branches:
      - master
      - docker

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

    - name: Install Docker and Docker Compose on EC2
      run: |
        ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Instalar Docker y Docker Compose
          sudo apt-get update
          sudo apt-get install -y docker.io curl

          # Instalar Docker Compose
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

          # Habilitar Docker
          sudo systemctl enable --now docker
        EOF

    - name: Deploy to EC2
      run: |
        ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Asegurar que el directorio de destino tiene permisos de escritura
          sudo mount -o remount,rw /var/www/html

          # Eliminar el directorio antiguo y crear uno nuevo
          sudo rm -rf /var/www/html/projectdesarrollo
          sudo mkdir -p /var/www/html/projectdesarrollo

          # Clonar el repositorio si no existe
          if [ ! -d "/var/www/html/projectdesarrollo/.git" ]; then
            sudo git clone -b docker https://github.com/tjhoan/projectDesarrollo.git /var/www/html/projectdesarrollo
          fi

          # Establecer permisos adecuados
          sudo chown -R ubuntu:ubuntu /var/www/html/projectdesarrollo
          sudo chmod -R 755 /var/www/html/projectdesarrollo

          # Cambiar el nombre del archivo .env.docker a .env
          sudo mv /var/www/html/projectdesarrollo/.env.docker /var/www/html/projectdesarrollo/.env

          # Ejecutar el script init.sh
          sudo chmod +x /var/www/html/projectdesarrollo/init.sh
          sudo /var/www/html/projectdesarrollo/init.sh prod
        EOF
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        COMPOSER_PROCESS_TIMEOUT: 0
        COMPOSER_NO_INTERACTION: 1
        COMPOSER_NO_AUDIT: 1
