name: Deploy to EC2

on:
  push:
    branches:
      - master
      - docker
  pull_request:
    branches:
      - master
      - docker

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$EC2_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

    - name: Deploy to EC2 instance
      run: |
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          cd /var/www/html/projectdesarrollo
          sudo git pull origin docker
          sudo docker-compose down -v
          sudo docker system prune -a --volumes -f
          sudo docker-compose up --build -d
          sudo chown -R ubuntu:ubuntu /var/www/html/projectdesarrollo
          sudo chmod -R 755 /var/www/html/projectdesarrollo
        EOF
