name: Deploy to EC2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

    - name: Install Docker and Docker Compose on EC2
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Instalar Docker y Docker Compose si no están instalados
          if ! command -v docker &> /dev/null; then
            echo "Instalando Docker..."
            sudo apt update && sudo apt upgrade -y
            sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt update
            sudo apt install -y docker-ce
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo docker --version
          fi

          if ! command -v docker-compose &> /dev/null; then
            echo "Instalando Docker Compose..."
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

          # Asegurarse de que Docker pueda ser usado por el usuario
          sudo usermod -aG docker ubuntu
          newgrp docker
        EOF

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Remonta el sistema de archivos como lectura/escritura
          sudo mount -o remount,rw /

          # Crear un nuevo directorio para el proyecto
          sudo mkdir -p /home/ubuntu/projectdesarrollo
          sudo chmod -R 777 /home/ubuntu/projectdesarrollo
          sudo chown -R ubuntu:ubuntu /home/ubuntu/projectdesarrollo

          # Eliminar el proyecto anterior y clonar el repositorio
          if [ -d "/home/ubuntu/projectdesarrollo/.git" ]; then
            cd /home/ubuntu/projectdesarrollo
            sudo git pull origin docker
          else
            sudo git clone https://github.com/tjhoan/projectDesarrollo.git /home/ubuntu/projectdesarrollo
          fi

          # Ejecutar el script init.sh
          cd /home/ubuntu/projectdesarrollo
          sudo chmod +x init.sh
          sudo ./init.sh
        EOF

      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        COMPOSER_PROCESS_TIMEOUT: 0
        COMPOSER_NO_INTERACTION: 1
        COMPOSER_NO_AUDIT: 1
